services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - bundle:/usr/local/bundle
      - ./:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: ['bundle', 'exec', 'rails', 's', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: development
  mongo:
    image: mongo


volumes:
  bundle:
    driver: local
